### ISSUE TITLE
Add [build-system] to pyproject.toml for PEP 517/518 compatibility

### ISSUE THREAD

**Issue by PilCAki** [PilCAki/chaincollections#43]
The repository's pyproject.toml currently only configures Black and isort, but does not declare a `[build-system]` section. This is not strictly required for traditional `setup.py` builds but is recommended for PEP 517/518 compatibility and modern Python packaging tools.

**Suggested Fix:**
- Add a `[build-system]` section to pyproject.toml for better compatibility:

```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

This ensures that modern tools like pip, build, and PyPI can correctly build your package.
